### ISSUE TITLE
ResampleNoDataTiles to resolve Silverlight 3.2 regression?

### ISSUE THREAD

**Issue by gobsmack** [Esri/arcgis-samples-silverlight#3] opened 2014-08-19 21:21 UTC
A few people, myself included, have had trouble with what seems like Silverlight API 3.2 no longer displaying tiles when zoomed to the service's max scale, or beyond. I'm seeing this with my services, and also the AGO basemaps. I'm looking at the ResampleNoDataTiles sample by @rexhansen. If the issue is by design, is that was this sample is addressing?

**Comment by rexhansen** [comment] 2015-02-03 03:52
@gobsmack This is was by design in 3.2.  Min and max scale advertised by the service were applied to the layer.  Unfortunately setting the min and max resolution on the layer or map did not override service settings.  This bug (NIM104466) has been fixed in the API in version 3.3.   

Note, the ResampleNoDataTiles sample merely shows how to replace no data tiles with tiles that contain data (up sampling to a level which contains data).  It is\was not a workaround for overriding the service min and max scale limits.

**Closed** 2015-02-03 03:54 UTC
